// Shared styles for Employee and Employer forms
const styles = {
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: '"Inter", sans-serif',
    backgroundColor: '#f5f5f5',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    marginBottom: '30px',
    backgroundColor: '#fff',
    padding: '20px',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  logo: {
    height: '60px',
    width: 'auto',
  },
  headerText: {
    flex: 1,
  },
  title: {
    margin: '0',
    fontSize: '28px',
    fontWeight: '600',
    color: '#0052a3',
    fontFamily: '"Plus Jakarta Sans", sans-serif',
  },
  tagline: {
    margin: '5px 0 0 0',
    fontSize: '14px',
    color: '#666',
  },
  progressContainer: {
    marginBottom: '30px',
    backgroundColor: '#fff',
    padding: '20px',
    borderRadius: '8px',
  },
  progressBar: {
    display: 'flex',
    gap: '8px',
    marginBottom: '10px',
    justifyContent: 'space-between',
  },
  progressStep: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: '600',
    color: '#fff',
    transition: 'background-color 0.3s',
  },
  stepNumber: {
    display: 'block',
  },
  stepLabels: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#666',
  },
  stepLabel: {
    flex: 1,
    textAlign: 'center',
  },
  content: {
    backgroundColor: '#fff',
    padding: '30px',
    borderRadius: '8px',
    marginBottom: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  stepTitle: {
    fontSize: '24px',
    fontWeight: '600',
    color: '#0052a3',
    marginBottom: '20px',
    fontFamily: '"Plus Jakarta Sans", sans-serif',
  },
  stepDescription: {
    color: '#666',
    marginBottom: '20px',
    lineHeight: '1.5',
  },
  subTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#003d7a',
    marginTop: '20px',
    marginBottom: '15px',
    fontFamily: '"Plus Jakarta Sans", sans-serif',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '20px',
    marginBottom: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#333',
    marginBottom: '8px',
  },
  input: {
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #ccc',
    borderRadius: '4px',
    fontFamily: 'inherit',
    transition: 'border-color 0.3s',
  },
  fileInput: {
    padding: '8px',
    fontSize: '14px',
  },
  checkbox: {
    marginRight: '8px',
    cursor: 'pointer',
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '15px',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '14px',
    cursor: 'pointer',
    color: '#333',
  },
  error: {
    color: '#d32f2f',
    fontSize: '12px',
    marginTop: '4px',
  },
  uploadSuccess: {
    color: '#2e7d32',
    fontSize: '12px',
    marginTop: '4px',
  },
  helpText: {
    fontSize: '12px',
    color: '#999',
    marginTop: '6px',
    fontStyle: 'italic',
  },
  pdfViewer: {
    marginTop: '20px',
    padding: '20px',
    backgroundColor: '#f9f9f9',
    borderRadius: '4px',
    border: '1px solid #e0e0e0',
  },
  pdfFrame: {
    width: '100%',
    height: '600px',
    border: 'none',
    marginBottom: '15px',
    borderRadius: '4px',
  },
  reviewSection: {
    marginBottom: '20px',
    padding: '15px',
    backgroundColor: '#f9f9f9',
    borderRadius: '4px',
    borderLeft: '4px solid #0052a3',
  },
  signatureSection: {
    marginTop: '30px',
    padding: '20px',
    backgroundColor: '#e3f2fd',
    borderRadius: '4px',
    borderLeft: '4px solid #0052a3',
  },
  navigation: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'space-between',
  },
  button: {
    padding: '12px 30px',
    fontSize: '14px',
    fontWeight: '600',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  backButton: {
    backgroundColor: '#e0e0e0',
    color: '#333',
  },
  continueButton: {
    backgroundColor: '#0052a3',
    color: '#fff',
    marginLeft: 'auto',
  },
  submitButton: {
    backgroundColor: '#2e7d32',
    color: '#fff',
    marginLeft: 'auto',
  },
  errorBanner: {
    backgroundColor: '#ffebee',
    border: '1px solid #ef5350',
    color: '#c62828',
    padding: '15px',
    borderRadius: '4px',
    marginBottom: '20px',
    fontSize: '14px',
  },
  successContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    padding: '20px',
  },
  successCard: {
    backgroundColor: '#fff',
    padding: '40px',
    borderRadius: '8px',
    textAlign: 'center',
    maxWidth: '500px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  successIcon: {
    fontSize: '60px',
    color: '#2e7d32',
    marginBottom: '20px',
  },
  successTitle: {
    fontSize: '28px',
    fontWeight: '600',
    color: '#0052a3',
    marginBottom: '15px',
    fontFamily: '"Plus Jakarta Sans", sans-serif',
  },
  successMessage: {
    fontSize: '16px',
    color: '#666',
    marginBottom: '20px',
    lineHeight: '1.6',
  },
  submissionId: {
    fontSize: '12px',
    color: '#999',
    marginBottom: '20px',
    fontFamily: 'monospace',
  },
  nextSteps: {
    fontSize: '14px',
    color: '#666',
    fontStyle: 'italic',
  },
};

const employerStyles = {
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '40px 20px',
    fontFamily: "'Inter', sans-serif",
    backgroundColor: '#f9fafb',
    minHeight: '100vh',
  },
  header: {
    textAlign: 'center',
    marginBottom: '40px',
    borderBottom: '1px solid #e5e7eb',
    paddingBottom: '20px',
  },
  logo: {
    height: '50px',
    marginBottom: '20px',
  },
  progressBar: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginBottom: '40px',
  },
  progressStep: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    color: '#666',
    backgroundColor: '#e0e0e0',
    transition: 'all 0.3s ease',
  },
  form: {
    backgroundColor: 'white',
    borderRadius: '8px',
    padding: '40px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  step: {
    marginBottom: '40px',
  },
  stepDescription: {
    color: '#666',
    marginBottom: '20px',
    lineHeight: '1.6',
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '20px',
    marginBottom: '30px',
  },
  summaryField: {
    backgroundColor: '#f3f4f6',
    padding: '15px',
    borderRadius: '6px',
  },
  summaryValue: {
    fontSize: '16px',
    fontWeight: '500',
    color: '#1f2937',
    margin: '8px 0 0 0',
  },
  bankAccountsSection: {
    marginTop: '30px',
    paddingTop: '30px',
    borderTop: '1px solid #e5e7eb',
  },
  bankAccount: {
    backgroundColor: '#f3f4f6',
    padding: '15px',
    borderRadius: '6px',
    marginBottom: '10px',
  },
  formGroup: {
    marginBottom: '20px',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontWeight: '500',
    color: '#374151',
    fontSize: '14px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    fontFamily: "'Inter', sans-serif",
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  checkboxGroup: {
    marginBottom: '15px',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '14px',
    color: '#374151',
    cursor: 'pointer',
  },
  checkbox: {
    marginRight: '10px',
    cursor: 'pointer',
    width: '18px',
    height: '18px',
  },
  allowancesSection: {
    backgroundColor: '#f3f4f6',
    padding: '15px',
    borderRadius: '6px',
    marginTop: '15px',
    marginBottom: '20px',
  },
  divider: {
    height: '1px',
    backgroundColor: '#e5e7eb',
    margin: '30px 0',
  },
  helpText: {
    color: '#6b7280',
    fontSize: '13px',
    marginBottom: '15px',
    lineHeight: '1.5',
  },
  toggleButton: {
    padding: '10px 16px',
    backgroundColor: '#f3f4f6',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: '#374151',
    marginBottom: '20px',
    transition: 'all 0.2s',
  },
  payNoticeContainer: {
    marginBottom: '30px',
    padding: '20px',
    backgroundColor: '#f9fafb',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
  },
  pdfViewer: {
    width: '100%',
    height: '600px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
  },
  reviewSection: {
    backgroundColor: '#f3f4f6',
    padding: '20px',
    borderRadius: '6px',
    marginBottom: '30px',
  },
  reviewCategory: {
    marginBottom: '20px',
  },
  certificationBox: {
    backgroundColor: '#e8f3ff',
    border: '1px solid #0052a3',
    borderRadius: '6px',
    padding: '20px',
    marginBottom: '30px',
  },
  buttonGroup: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
    marginTop: '30px',
  },
  buttonPrimary: {
    padding: '12px 24px',
    backgroundColor: '#0052a3',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
  },
  buttonSecondary: {
    padding: '12px 24px',
    backgroundColor: 'white',
    color: '#0052a3',
    border: '2px solid #0052a3',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
  },
  errorBox: {
    backgroundColor: '#fee',
    border: '1px solid #fcc',
    borderRadius: '8px',
    padding: '30px',
    textAlign: 'center',
    color: '#c33',
  },
  errorBanner: {
    backgroundColor: '#fee',
    border: '1px solid #fcc',
    borderRadius: '6px',
    padding: '15px',
    marginBottom: '20px',
    color: '#c33',
    fontSize: '14px',
  },
  errorBannerBottom: {
    backgroundColor: '#fee',
    border: '1px solid #fcc',
    borderRadius: '6px',
    padding: '15px',
    marginTop: '20px',
    color: '#c33',
    fontSize: '14px',
  },
  successBox: {
    backgroundColor: '#ecf5ec',
    border: '1px solid #4caf50',
    borderRadius: '8px',
    padding: '40px',
    textAlign: 'center',
    color: '#2e7d32',
  },
  successIcon: {
    fontSize: '48px',
    marginBottom: '20px',
    color: '#4caf50',
  },
  successSubtext: {
    color: '#558b2f',
    fontSize: '14px',
    marginTop: '15px',
  },
  center: {
    textAlign: 'center',
    padding: '60px 20px',
  },
  spinner: {
    width: '40px',
    height: '40px',
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #0052a3',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
    margin: '0 auto 20px',
  },
};